// Generated by CoffeeScript 1.3.3
(function() {
  var fibsUpto, num, result;

  fibsUpto = function(limit) {
    var current, list, oldcurr, temp;
    list = [1];
    oldcurr = 0;
    current = 1;
    while (current < limit) {
      list.push(current);
      temp = oldcurr;
      oldcurr = current;
      current = temp + current;
    }
    return list;
  };

  result = (function() {
    var _i, _len, _ref, _results;
    _ref = fibsUpto(4000000);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      num = _ref[_i];
      if (num % 2 === 0) {
        _results.push(num);
      }
    }
    return _results;
  })();

  result = result.reduce(function(x, y) {
    return x + y;
  });

  console.log(result);

}).call(this);
